# kudaw-delivery: v1.8.0
#
# The delivery process, identical in every Kudaw repo. Included by the repo's Makefile,
# which adds only what genuinely varies: the quality-gate stages of its stack.
#
#     ROOT := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
#     include delivery.mk
#     check: ; @cd app && bun run check:all
#     lint:  ; @cd app && bun run lint
#     ...
#
# DO NOT EDIT THIS FILE IN A REPO. It carries a seal and `/cicd audit` compares it against
# the canonical copy in kudaw-tecnica/tech-cicd. A local edit is either something that
# belongs in `delivery.conf`, or a change the contract should absorb for everyone — take
# it there instead of forking it here.
#
# Contract: kudaw-tecnica/tech-cicd, references/comandos-proceso.md.

SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := help

# Self-locating: at the moment this file is read, it is the last one in MAKEFILE_LIST.
DELIVERY_ROOT := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
DELIVERY_SCRIPTS := $(DELIVERY_ROOT)/scripts

# What the repo's own task runner is, for the help footer. The repo's Makefile may set it.
DELIVERY_TASKS_HINT ?= your stack's task runner

# The profile decides which artifact slot this repo gets. Read from delivery.conf rather
# than configured twice — the conf is the one place a repo describes itself.
DELIVERY_PROFILE := $(shell bash -c 'source $(DELIVERY_ROOT)/delivery.conf 2>/dev/null; echo "$$PROFILE"')

# In a monorepo every version command takes PKG=<name>. Exported so the scripts see it as
# an environment variable, not just as a make variable.
export PKG

# Pass a value with spaces through to the shell as one argument.
shellquote = '$(subst ','\'',$(1))'

define delivery_version
$(shell bash $(DELIVERY_SCRIPTS)/version.sh get)
endef

# --- help ---------------------------------------------------------------------

## General
.PHONY: help
# awk reads the makefile as TEXT, so without DELIVERY_HIDE it prints both branches of the
# profile conditional and offers targets this repo does not define. Someone reads the help,
# runs `make image` and gets "No rule to make target" — worse than never listing it. The
# section header is held back until a target under it survives the filter, so a section
# that belongs entirely to the other profile does not print an empty heading.
DELIVERY_SLOT_ALL := package publish verify promote-main image-registry image-status image promote-staging promote-prod
# Deferred (=, not :=): DELIVERY_SLOT is set inside the profile conditional further down,
# so an immediate expansion here would see it empty and hide every slot target.
DELIVERY_HIDE = $(filter-out $(DELIVERY_SLOT),$(DELIVERY_SLOT_ALL))

help: ## Show this help
	@DELIVERY_HIDE='$(DELIVERY_HIDE)' awk 'BEGIN {FS = ":.*## "; \
			split(ENVIRON["DELIVERY_HIDE"], h, " "); for (i in h) hide[h[i]] = 1; \
			print "Delivery targets (day-to-day work: $(DELIVERY_TASKS_HINT))\n"} \
		/^## /                 { section = substr($$0, 4); pending = 1; next } \
		/^[a-z][a-z0-9-]*:.*## / { if ($$1 in hide) next; \
			if (pending) { printf "\n\033[1m%s\033[0m\n", section; pending = 0 } \
			printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2 }' \
		$(MAKEFILE_LIST)

## Status
.PHONY: status version baseline suggest-level manifest
status: ## Version/release/artifact drift report (informational, never blocks)
	@bash $(DELIVERY_ROOT)/scripts/version-status.sh $(ARGS)

version: ## Print the current version
	@bash $(DELIVERY_SCRIPTS)/version.sh get

baseline: ## Print the tag that "since last release" ranges start from
	@bash $(DELIVERY_SCRIPTS)/version.sh baseline

suggest-level: ## Suggest a bump level from the commits since the last release
	@bash $(DELIVERY_SCRIPTS)/version.sh suggest $(ARGS)

manifest: ## Print the manifest path, relative to the repo root
	@bash $(DELIVERY_SCRIPTS)/version.sh manifest

## Version
# `bump` and `set-version` write the manifest and stop there — they never commit. The
# commit is closed by `changelog`, which carries the version bump and the changelog entry
# together, so a released version always has its entry.
.PHONY: bump set-version changelog
bump: ## Write the next version. LEVEL=patch|minor|major
	@test -n "$(LEVEL)" || { echo "Usage: make bump LEVEL=patch|minor|major" >&2; exit 2; }
	@bash $(DELIVERY_SCRIPTS)/version.sh bump $(LEVEL)

set-version: ## Write an explicit version. VERSION=x.y.z
	@test -n "$(VERSION)" || { echo "Usage: make set-version VERSION=x.y.z" >&2; exit 2; }
	@bash $(DELIVERY_SCRIPTS)/version.sh set $(VERSION)

changelog: ## Write the CHANGELOG entry. VERSION=x.y.z (default: current), TITLE="..."
	@TITLE=$(call shellquote,$(TITLE)) bash $(DELIVERY_SCRIPTS)/changelog.sh add \
		$(or $(VERSION),$(delivery_version))

## Artifact
# One slot, two shapes. A service ships an image in one step; a library and a Splunk app
# ship in three (preview -> publish -> verify). A repo gets the pair its profile calls for,
# so `contract-check` finds what it requires and nothing it does not.
#
# A Splunk app takes the three-step shape, not the image one: what it ships is a packaged
# `.tar.gz` attached to a GitHub Release, it has no registry to push to and no staging
# environment to deploy to. What plays the part of staging is `verify` — the artifact has
# to be built and green before main advances — so it promotes develop -> main like a
# library does.
#
# Both delegate to a script of the repo, the way `status` delegates to version-status.sh:
# WHAT the artifact is, and where it goes, is the one thing the contract cannot generalise.
ifneq ($(filter $(DELIVERY_PROFILE),libreria app-splunk),)
.PHONY: verify promote-main

# The slot's verb is the profile's own. A library PUBLISHES — `publish` uploads to the
# registry. A Splunk app PACKAGES — nothing is uploaded until `release` attaches the
# .tar.gz — so calling it `publish` would mean the same command uploads there and only
# builds here, which is the divergence the canonical names exist to prevent.
ifeq ($(DELIVERY_PROFILE),app-splunk)
DELIVERY_SLOT := package verify promote-main
.PHONY: package
package: ## Build the artifact. DRY_RUN=0 for the release one, DEV=1 for one to try
	@bash $(DELIVERY_ROOT)/scripts/package.sh $(if $(DEV),--dev,$(if $(filter 0,$(DRY_RUN)),,--dry-run))
else
DELIVERY_SLOT := publish verify promote-main
.PHONY: publish
publish: ## Preview the package. DRY_RUN=0 to actually publish. PKG= selects one
	@bash $(DELIVERY_ROOT)/scripts/publish.sh $(if $(filter 0,$(DRY_RUN)),,--dry-run)
endif

verify: ## Confirm the published version is visible in the registry
	@bash $(DELIVERY_ROOT)/scripts/verify.sh $(ARGS)

promote-main: ## Merge develop -> main and push. Run it after verify is green
	@bash $(DELIVERY_SCRIPTS)/promote.sh main
else
DELIVERY_SLOT := image-registry image-status image promote-staging promote-prod
.PHONY: image-status image image-registry
image-registry: ## Print the registry host the image is published to
	@bash -c 'source $(DELIVERY_ROOT)/delivery.conf; echo "$$REGISTRY"'

image-status: ## Local version, local build state and registry state of the tag
	@bash $(DELIVERY_ROOT)/scripts/docker-image.sh status

# SUFFIX appends to the version tag, for a CI preview build off an integration branch
# (`0.11.1-dev.2609101430`). It is the same build definition either way — a second one,
# spelled out in a workflow, is how CI and the terminal drift apart.
image: ## Build + publish the versioned image to ACR. FORCE=1 to replace a published tag
	@bash $(DELIVERY_ROOT)/scripts/docker-image.sh full $(if $(FORCE),--force,) $(if $(SUFFIX),--suffix=$(SUFFIX),)

# Promoting through an environment branch belongs to the profile that HAS one. A library
# and a Splunk app go develop -> main, so offering them `promote-staging` offers a target
# that merges into a `testing` branch their repo never created.
.PHONY: promote-staging promote-prod
promote-staging: ## Merge develop -> testing and push (triggers the staging deploy)
	@bash $(DELIVERY_SCRIPTS)/promote.sh staging

promote-prod: ## Merge testing -> main and push (triggers the production deploy)
	@bash $(DELIVERY_SCRIPTS)/promote.sh prod
endif

## Release
.PHONY: release-notes release
release-notes: ## Categorised notes to stdout. VERSION=x.y.z (default: current)
	@bash $(DELIVERY_SCRIPTS)/release-notes.sh $(or $(VERSION),$(delivery_version))

release: ## Annotated tag on origin/main + GitHub Release. VERSION=x.y.z (default: current)
	@bash $(DELIVERY_SCRIPTS)/release.sh $(or $(VERSION),$(delivery_version))

## Validation
.PHONY: contract-check self-test
contract-check: ## Does this repo expose the surface its profile requires? WARN=1 to not fail
	@bash $(DELIVERY_SCRIPTS)/contract-check.sh $(if $(WARN),--warn,)

self-test: ## Do the deterministic targets do what they say?
	@bash $(DELIVERY_SCRIPTS)/self-test.sh
