#!/usr/bin/env python3
"""Read matrix.yml and emit the .env for one profile.

    python3 matrix.py nifi2-current      # print the .env
    python3 matrix.py --ci pull_request  # print the profile names CI runs

PyYAML is used when available. The CI container's dependencies are not
guaranteed, so there is a fallback parser for the small subset of YAML this
file uses (two-space nesting, `key: value`, `- item` lists, and `>` folded
blocks for the descriptions).
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MATRIX = os.path.join(HERE, "matrix.yml")

# Host ports. Fixed rather than random so the URLs in README stay true and a
# developer can point a browser at a running stack.
PORTS = {
    "SPLUNK_WEB_PORT": "38000",
    "SPLUNK_MGMT_PORT": "38089",
    "SPLUNK_HEC_PORT": "38088",
    "NIFI_HTTP_PORT": "38080",
    "NIFI_HTTPS_PORT": "38443",
}

SPLUNK_PASSWORD = "Password123"
SPLUNK_HEC_TOKEN = "00000000-0000-0000-0000-0000000000ab"


def _unquote(value):
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def _parse_minimal_yaml(text):
    """Parse the subset of YAML used by matrix.yml.

    Supports nested mappings by indentation, `- item` sequences and `>`
    folded scalars. Deliberately not a general YAML parser: it exists only so
    the harness does not depend on PyYAML being present in the CI container,
    and test_matrix.py asserts it agrees with PyYAML on the real file.
    """
    lines = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        lines.append((len(raw) - len(raw.lstrip()), stripped))

    position = [0]

    def parse_block(min_indent):
        _, first = lines[position[0]]
        if first.startswith("- "):
            items = []
            while position[0] < len(lines):
                indent, content = lines[position[0]]
                if indent < min_indent or not content.startswith("- "):
                    break
                items.append(_unquote(content[2:].strip()))
                position[0] += 1
            return items

        mapping = {}
        while position[0] < len(lines):
            indent, content = lines[position[0]]
            if indent < min_indent:
                break
            if ":" not in content:
                raise ValueError("cannot parse line: %r" % content)
            key, _, value = content.partition(":")
            key, value = key.strip(), value.strip()
            position[0] += 1

            if value in (">", "|", ">-", "|-"):
                folded = []
                while position[0] < len(lines) and lines[position[0]][0] > indent:
                    folded.append(lines[position[0]][1])
                    position[0] += 1
                joined = " ".join(folded)
                # `>` and `|` keep a trailing newline; the stripping forms
                # (`>-`, `|-`) do not. Match PyYAML so the parity test can
                # compare the two readers exactly.
                mapping[key] = joined if value.endswith("-") else joined + "\n"
            elif value == "":
                if position[0] < len(lines) and lines[position[0]][0] > indent:
                    mapping[key] = parse_block(lines[position[0]][0])
                else:
                    mapping[key] = None
            else:
                mapping[key] = _unquote(value)
        return mapping

    return parse_block(0) if lines else {}


def load():
    text = open(MATRIX).read()
    try:
        import yaml
        return yaml.safe_load(text)
    except ImportError:
        return _parse_minimal_yaml(text)


def env_for(profile_name):
    data = load()
    profiles = data["profiles"]
    if profile_name not in profiles:
        raise SystemExit(
            "unknown profile '%s'; known: %s"
            % (profile_name, ", ".join(sorted(profiles)))
        )
    profile = profiles[profile_name]
    auth = profile["nifi_auth"]

    lines = [
        "# Generated by matrix.py from matrix.yml -- do not edit by hand.",
        "PROFILE=%s" % profile_name,
        "NIFI_VERSION=%s" % profile["nifi_version"],
        "SPLUNK_VERSION=%s" % profile["splunk_version"],
        "NIFI_AUTH=%s" % auth,
        "NIFI_ENV_FILE=./env/nifi-%s.env" % auth,
        "SPLUNK_PASSWORD=%s" % SPLUNK_PASSWORD,
        "SPLUNK_HEC_TOKEN=%s" % SPLUNK_HEC_TOKEN,
    ]
    lines += ["%s=%s" % item for item in sorted(PORTS.items())]
    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) >= 2 and argv[0] == "--ci":
        for name in load()["ci"][argv[1]]:
            print(name)
        return 0
    if not argv:
        raise SystemExit("usage: matrix.py <profile> | --ci <pull_request|release>")
    sys.stdout.write(env_for(argv[0]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
