[launcher]
description = Add-on to normalize fields from NiFi Reporting Tasks and Metrics
author = Kudaw
version = 2.0.0

[package]
id = nifi_TA_monitoring
check_for_updates = true

[ui]
is_visible = false
label = NiFi TA Monitoring

[id]
name = nifi_TA_monitoring
version = 2.0.0
