#!/bin/sh
# Seed /opt/splunkforwarder/etc before the Universal Forwarder's first boot.
#
# Same trick as seed-splunk-etc.sh: the image extracts its own etc/
# additively on first start, so what is placed here survives.
#
# The forwarder gets the real TA, not a bespoke inputs.conf, so the profile
# exercises the monitor stanzas as shipped. Only `disabled` and `index` are
# overridden, in local/.
#
# Runs in a busybox container: POSIX sh only, no bash.

set -eu

# --bare: bring the environment up and install nothing. Splunk then extracts
# its own etc/ into the empty volume on first boot, which is a virgin Splunk
# -- no apps, no inputs, no HEC, no index. The point is the one path the
# automated profiles cannot cover, because they exist to remove it: what an
# operator actually does, from uploading the .tar.gz to filling in the form.
if [ "${BARE:-0}" = "1" ]; then
    echo "seed: BARE=1, installing nothing"
    exit 0
fi


SEED=/etc-seed
SRC=/src

# nifi_TA_monitoring is generated by ucc-gen and lives in output/; the app is
# not and lives in the tree. Seeding the TA from the tree would install an
# add-on with no app.conf, no inputs.conf and no UI -- it would look like it
# installed and then do nothing. Fail loudly instead (UI-3).
app_source() {
    case "$1" in
        nifi_TA_monitoring)
            if [ ! -d "$SRC/output/nifi_TA_monitoring" ]; then
                echo "seed: FATAL output/nifi_TA_monitoring is missing; run tests/build-ta.sh" >&2
                exit 1
            fi
            echo "$SRC/output/nifi_TA_monitoring"
            ;;
        *) echo "$SRC/$1" ;;
    esac
}
# Which NiFi this forwarder sits next to. UF_HOST is what the events are
# stamped with; UF_NODE, when set, adds an indexed `node` field so a cluster's
# logs say which member they came from while still sharing one host (the
# cluster is the instance -- decision C-1).
UF_HOST="${UF_HOST:-nifi}"
UF_NODE="${UF_NODE:-}"

echo "seed-uf: installing the TA"
mkdir -p "$SEED/apps"
rm -rf "$SEED/apps/nifi_TA_monitoring"
cp -r "$(app_source nifi_TA_monitoring)" "$SEED/apps/nifi_TA_monitoring"
find "$SEED/apps/nifi_TA_monitoring" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

# A forwarder must not run the modular input: that is the indexer's job here,
# and two collectors would duplicate every API event.
mkdir -p "$SEED/apps/nifi_TA_monitoring/local"
echo "seed-uf: enabling the log monitors, leaving the modular input off"
sed -e "s/^host = nifi$/host = $UF_HOST/" \
    "$SRC/tests/provision/uf/inputs.conf" \
    > "$SEED/apps/nifi_TA_monitoring/local/inputs.conf"
if [ -n "$UF_NODE" ]; then
    echo "seed-uf: tagging events with node=$UF_NODE"
    sed -i "/^host = /a _meta = node::$UF_NODE" \
        "$SEED/apps/nifi_TA_monitoring/local/inputs.conf"
fi

echo "seed-uf: pointing outputs at the indexer"
mkdir -p "$SEED/system/local"
cat > "$SEED/system/local/outputs.conf" <<'CONF'
[tcpout]
defaultGroup = indexer

[tcpout:indexer]
server = splunk:9997

[tcpout-server://splunk:9997]
CONF

# Ownership: the forwarder image runs as uid 41812 (user "splunk").
chown -R 41812:41812 "$SEED" 2>/dev/null || true

echo "seed-uf: done"
