#!/bin/sh
# Seed /opt/splunk/etc before splunkd's first boot.
#
# The Splunk image extracts its own etc/ additively on first start, so files
# placed here survive. Seeding beforehand replaces the manual step the old
# harness required (docker exec into the container, copy the apps by hand,
# then turn off SSL on the HEC in the UI).
#
# Runs in a busybox container: POSIX sh only, no bash.

set -eu

SEED=/etc-seed
SRC=/src

# nifi_TA_monitoring is generated by ucc-gen and lives in output/; the app is
# not and lives in the tree. Seeding the TA from the tree would install an
# add-on with no app.conf, no inputs.conf and no UI -- it would look like it
# installed and then do nothing. Fail loudly instead (UI-3).
app_source() {
    case "$1" in
        nifi_TA_monitoring)
            if [ ! -d "$SRC/output/nifi_TA_monitoring" ]; then
                echo "seed: FATAL output/nifi_TA_monitoring is missing; run tests/build-ta.sh" >&2
                exit 1
            fi
            echo "$SRC/output/nifi_TA_monitoring"
            ;;
        *) echo "$SRC/$1" ;;
    esac
}

echo "seed: installing apps"
mkdir -p "$SEED/apps"
for app in nifi_monitoring nifi_TA_monitoring; do
    rm -rf "$SEED/apps/$app"
    cp -r "$(app_source "$app")" "$SEED/apps/$app"
    # __pycache__ from a host-side test run must not reach the container
    find "$SEED/apps/$app" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true
    echo "seed:   $app"
done

echo "seed: installing bundled third-party apps"
for tgz in "$SRC"/tests/additional_apps/*.tgz; do
    [ -f "$tgz" ] || continue
    tar -xzf "$tgz" -C "$SEED/apps"
    echo "seed:   $(basename "$tgz")"
done

echo "seed: enabling HEC without SSL"
# The documented workaround was to turn this off by hand in the UI after
# every start. Doing it in system/local makes the environment reproducible.
mkdir -p "$SEED/system/local"
cat > "$SEED/system/local/inputs.conf" <<'EOF'
[http]
disabled = 0
enableSSL = 0
port = 8088

[http://nifi]
disabled = 0
token = 00000000-0000-0000-0000-0000000000ab
index = nifi

# Receiving port for the Universal Forwarder. Only the forwarder profile
# connects to it; leaving it enabled everywhere costs nothing and keeps the
# seeded config identical across profiles.
[splunktcp://9997]
disabled = 0
EOF

# The input has to match the auth mode of the NiFi that is coming up: the
# unsecured profile talks plain HTTP on 8080, the single-user profile needs
# HTTPS on 8443 plus credentials. NIFI_AUTH comes from the compose file.
AUTH="${NIFI_AUTH:-none}"
echo "seed: configuring the TA input for auth=$AUTH"
INPUT_SRC="$SRC/tests/provision/splunk/inputs.conf.$AUTH"
# The cluster profile runs unsecured NiFi like the push profile does, but it
# collects through the modular input, so it needs the input enabled.
# ...but only when the add-on is the collector. A clustered profile that
# pushes keeps the disabled input of its auth mode: both paths at once
# duplicates every event.
if [ "${CLUSTER:-0}" = "1" ] && [ "${COLLECTION:-pull}" != "hec" ]; then
    INPUT_SRC="$SRC/tests/provision/splunk/inputs.conf.cluster"
fi
if [ ! -f "$INPUT_SRC" ]; then
    echo "seed: FATAL no input template for auth mode '$AUTH'" >&2
    exit 1
fi
mkdir -p "$SEED/apps/nifi_TA_monitoring/local"
cp "$INPUT_SRC" "$SEED/apps/nifi_TA_monitoring/local/inputs.conf"

# The tlsverify profile turns verification on and points the input at the
# bundle exported from NiFi. Rewritten rather than appended: a duplicated key
# in the same stanza is legal but reads as a mistake.
if [ "${TLS_VERIFY:-0}" = "1" ]; then
    echo "seed: verifying NiFi's certificate against the exported bundle"
    sed -i \
        -e "s|^verify_tls = 0|verify_tls = 1\nca_bundle = /opt/nifi-certs/nifi.pem|" \
        "$SEED/apps/nifi_TA_monitoring/local/inputs.conf"
fi

# More than one instance means a second input stanza appended to the same
# file. INSTANCES comes from the compose file.
if [ "${INSTANCES:-1}" -gt 1 ]; then
    echo "seed: adding the second instance input"
    printf '\n' >> "$SEED/apps/nifi_TA_monitoring/local/inputs.conf"
    cat "$SRC/tests/provision/splunk/inputs.conf.multi" \
        >> "$SEED/apps/nifi_TA_monitoring/local/inputs.conf"
fi

# A push profile must not also poll: both paths at once duplicates every
# event. This runs LAST, after any extra stanza has been appended -- an
# earlier version ran before that and left the second instance's input
# enabled, so a two-instance push profile collected through both paths.
#
# Idempotent by construction: strip whatever `disabled` lines are there and
# put one under every stanza. A `grep -q` guard is not enough, because a
# template that already carries one made the whole step a no-op.
if [ "${COLLECTION:-pull}" = "hec" ]; then
    echo "seed: push profile, disabling every TA input"
    # `a` rather than a `0,/re/s//&\n/` substitution: this runs in busybox,
    # whose sed ignores that form silently -- no error, no change.
    sed -i "/^disabled = /d" "$SEED/apps/nifi_TA_monitoring/local/inputs.conf"
    sed -i "/^\[nifi:\/\//a disabled = 1" \
        "$SEED/apps/nifi_TA_monitoring/local/inputs.conf"
fi

echo "seed: seeding the instance lookup"
mkdir -p "$SEED/apps/nifi_monitoring/lookups"
cp "$SRC/tests/provision/splunk/instance.csv" \
   "$SEED/apps/nifi_monitoring/lookups/instance.csv"

# Ownership: the Splunk image runs as uid 41812 (user "splunk").
chown -R 41812:41812 "$SEED" 2>/dev/null || true

echo "seed: done"
