"""Static checks on the app's Dashboard Studio views and alerts.

The views are generated by tools/gen_dashboards.py. These tests read what
ships -- the XML in nifi_monitoring/default/data/ui/views -- as data, and
catch the defects the redesign found by hand (docs/plans/
2026-10-01-rediseno-dashboards.md): a drilldown to a view that does not
exist (D-L), a view that opens waiting for input (D-J), a token that nothing
sets, a panel reading a dataset no source feeds.

Whether each panel returns rows is the integration suite's job
(DashboardPanelTest); this one needs no Splunk.
"""

import configparser
import json
import os
import re
import subprocess
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
APP = os.path.join(REPO, "nifi_monitoring")
VIEWS = os.path.join(APP, "default", "data", "ui", "views")
GENERATOR = os.path.join(REPO, "tools", "gen_dashboards.py")


def load_views():
    views = {}
    for name in sorted(os.listdir(VIEWS)):
        if not name.endswith(".xml"):
            continue
        text = open(os.path.join(VIEWS, name), encoding="utf-8").read()
        match = re.search(r"<definition><!\[CDATA\[(.*)\]\]></definition>", text, re.S)
        views[name[:-4]] = (text, json.loads(match.group(1)) if match else None)
    return views


def queries(definition):
    for ds_id, ds in definition["dataSources"].items():
        yield ds_id, ds["options"].get("query", "")


def conf(path):
    """A .conf file, with Splunk's backslash line continuation joined."""
    text = open(path, encoding="utf-8").read()
    text = re.sub(r"\\\n", "\n ", text)
    text = "\n".join(line for line in text.split("\n") if not line.lstrip().startswith("#"))
    parser = configparser.RawConfigParser(strict=False, interpolation=None)
    parser.optionxform = str
    parser.read_string(text)
    return parser


class GeneratedViewsTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.views = load_views()

    def test_the_views_are_what_the_generator_writes(self):
        """Edit tools/gen_dashboards.py, not the XML."""
        result = subprocess.run([sys.executable, GENERATOR, "--check"], capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_every_view_is_dashboard_studio(self):
        for name, (text, definition) in self.views.items():
            with self.subTest(view=name):
                self.assertIn('version="2"', text)
                self.assertIsNotNone(definition, "no JSON definition")

    def test_every_layout_item_exists(self):
        for name, (_, d) in self.views.items():
            for block in d["layout"]["structure"]:
                with self.subTest(view=name, item=block["item"]):
                    self.assertIn(block["item"], d["visualizations"])
            for input_id in d["layout"].get("globalInputs", []):
                with self.subTest(view=name, input=input_id):
                    self.assertIn(input_id, d["inputs"])

    def test_every_visualization_is_placed(self):
        for name, (_, d) in self.views.items():
            placed = {b["item"] for b in d["layout"]["structure"]}
            with self.subTest(view=name):
                self.assertEqual(set(d["visualizations"]) - placed, set())

    def test_every_data_source_reference_resolves(self):
        for name, (_, d) in self.views.items():
            specs = list(d["visualizations"].items()) + list(d["inputs"].items())
            for item_id, spec in specs:
                for ds in (spec.get("dataSources") or {}).values():
                    with self.subTest(view=name, item=item_id):
                        self.assertIn(ds, d["dataSources"])
            for ds_id, ds in d["dataSources"].items():
                if ds["type"] == "ds.chain":
                    with self.subTest(view=name, chain=ds_id):
                        self.assertIn(ds["options"]["extend"], d["dataSources"])

    def test_the_grid_rows_fill_the_width(self):
        for name, (_, d) in self.views.items():
            rows = {}
            for block in d["layout"]["structure"]:
                p = block["position"]
                rows.setdefault(p["y"], []).append(p)
            for y, cells in rows.items():
                with self.subTest(view=name, y=y):
                    self.assertEqual(sum(c["w"] for c in cells), d["layout"]["options"]["width"])


class ViewQueryTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.views = load_views()

    SOURCES = ("`index_nifi`", "datamodel=NIFI", "`nifi_fleet`", "inputlookup", "| rest ",
               "index=_internal", "index=_audit",
               # the diagnostic panel, the one place index=* is allowed (below)
               "where index=* sourcetype=nifi:*")

    def test_every_search_reads_through_the_app_s_entry_points(self):
        """The index_nifi macro, the NIFI datamodel, the fleet macro, a lookup
        or Splunk's own data -- never a hardcoded index."""
        for name, (_, d) in self.views.items():
            for ds_id, query in queries(d):
                if d["dataSources"][ds_id]["type"] == "ds.chain":
                    continue
                with self.subTest(view=name, ds=ds_id):
                    self.assertTrue(any(s in query for s in self.SOURCES), query[:120])
                    self.assertNotIn("index=nifi", query)

    def test_only_the_diagnostic_panel_may_scan_every_index(self):
        """index=* is defensible exactly once: the panel whose job is to find
        out where the data landed."""
        for name, (_, d) in self.views.items():
            for ds_id, query in queries(d):
                with self.subTest(view=name, ds=ds_id):
                    if "index=*" in query:
                        self.assertEqual((name, ds_id), ("nifi_collection_health", "ds_where"))

    def test_no_view_uses_a_join(self):
        """A join runs its right side as a subsearch, capped at 50k rows and
        60 s, and truncates silently past the cap."""
        for name, (text, _) in self.views.items():
            with self.subTest(view=name):
                self.assertNotRegex(text, r"\|\s*join\b")

    def test_no_panel_reads_the_push_only_datasets_directly(self):
        """D-A, D-C: Reporting_Task and Reporting_Bulletin only exist on the
        push path. Panels read the parents that cover both paths."""
        for name, (_, d) in self.views.items():
            for ds_id, query in queries(d):
                with self.subTest(view=name, ds=ds_id):
                    self.assertNotIn("NIFI.Reporting_", query)
                    self.assertNotIn("NIFI.Bulletin_Board", query)

    def test_free_text_never_filters_a_tstats(self):
        """D-O: a text term post-processing a tstats matches no field and
        empties the panel."""
        for name, (_, d) in self.views.items():
            for ds_id, ds in d["dataSources"].items():
                if ds["type"] != "ds.chain":
                    continue
                base = d["dataSources"][ds["options"]["extend"]]["options"].get("query", "")
                with self.subTest(view=name, ds=ds_id):
                    if "tstats" in base:
                        self.assertNotIn("$search$", ds["options"]["query"])


class DeprecationPanelTest(unittest.TestCase):
    """The Logs view's deprecations panel against a real nifi-deprecation.log event.

    NiFi writes each deprecation with the stack trace of the call that hit it,
    so the event is many lines long. The panel's rex used to end in `.+$`,
    which a multi-line event never matches: message came out null and
    `stats ... by message` dropped the row, so the panel stayed empty on the
    very instances it exists for. The integration suite cannot catch it -- a
    clean NiFi writes nothing to that log, so the panel is allowed to be empty
    there.
    """

    #: The first lines of what NiFi 1.28.1 wrote when a HashContent was added.
    EVENT = (
        "2026-10-01 20:11:33,710 WARN [NiFi Web Server-28] "
        "deprecation.org.apache.nifi.processors.standard.HashContent Added Deprecated "
        "Component HashContent[id=f917fbc9-01a0-1000-0f69-27eab934932d] See alternatives "
        "[org.apache.nifi.processors.standard.CryptographicHashContent]\n"
        "org.apache.nifi.deprecation.log.DeprecationException: Reference Class "
        "[org.apache.nifi.processors.standard.HashContent]\n"
        "\tat org.apache.nifi.deprecation.log.StandardDeprecationLogger"
        ".getExtendedArguments(StandardDeprecationLogger.java:63)\n"
    )

    def test_the_message_is_extracted_from_a_multi_line_event(self):
        _, definition = load_views()["nifi_logs"]
        query = definition["dataSources"]["ds_deprecations"]["options"]["query"]
        pattern = re.search(r'\| rex "(.*?)"\n', query).group(1)
        # SPL's rex is PCRE; Python spells named groups (?P<name>...).
        match = re.search(pattern.replace("(?<", "(?P<"), self.EVENT)
        self.assertIsNotNone(match, pattern)
        self.assertEqual(match.group("logger"),
                         "deprecation.org.apache.nifi.processors.standard.HashContent")
        self.assertTrue(match.group("message").startswith("Added Deprecated Component HashContent"))
        self.assertNotIn("\n", match.group("message"))


class NavigationTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.views = load_views()
        cls.nav = open(os.path.join(APP, "default", "data", "ui", "nav", "default.xml")).read()

    def test_every_drilldown_opens_a_view_that_exists(self):
        """D-L: the bulletin count linked to bulletin_monitor_panel."""
        for name, (_, d) in self.views.items():
            for viz_id, spec in d["visualizations"].items():
                for handler in spec.get("eventHandlers", []):
                    url = handler.get("options", {}).get("url")
                    if not url:
                        continue
                    target = re.match(r"/app/nifi_monitoring/([a-z_]+)", url)
                    with self.subTest(view=name, viz=viz_id):
                        self.assertIsNotNone(target, url)
                        self.assertIn(target.group(1), self.views)

    def test_every_drilldown_token_is_one_the_target_reads(self):
        for name, (_, d) in self.views.items():
            for viz_id, spec in d["visualizations"].items():
                for handler in spec.get("eventHandlers", []):
                    url = handler.get("options", {}).get("url", "")
                    target = re.match(r"/app/nifi_monitoring/([a-z_]+)", url)
                    if not target:
                        continue
                    inputs = self.views[target.group(1)][1]["inputs"].values()
                    tokens = {i["options"]["token"] for i in inputs}
                    tokens |= {t + suffix for t in tokens for suffix in (".earliest", ".latest")}
                    for token in re.findall(r"form\.([a-z_.]+)=", url):
                        with self.subTest(view=name, viz=viz_id, token=token):
                            self.assertIn(token, tokens)

    def test_every_view_is_in_the_navigation(self):
        for name in self.views:
            with self.subTest(view=name):
                self.assertIn('name="%s"' % name, self.nav)

    def test_the_navigation_names_no_missing_view(self):
        for name in re.findall(r'<view name="([^"]+)"', self.nav):
            with self.subTest(view=name):
                self.assertTrue(name == "search" or name in self.views, name)

    def test_every_drilldown_keeps_the_time_range(self):
        for name, (_, d) in self.views.items():
            for viz_id, spec in d["visualizations"].items():
                for handler in spec.get("eventHandlers", []):
                    url = handler.get("options", {}).get("url")
                    if url:
                        with self.subTest(view=name, viz=viz_id):
                            self.assertIn("form.time.earliest=$time.earliest$", url)

    def test_the_overview_is_the_landing_page(self):
        """D-H: the old landing page was a splash screen with no data."""
        self.assertRegex(self.nav, r'<view name="nifi_overview" default="true"')


class TokenTest(unittest.TestCase):

    BUILTIN = {"time.earliest", "time.latest"}

    @classmethod
    def setUpClass(cls):
        cls.views = load_views()

    def defined(self, d):
        tokens = set(self.BUILTIN)
        for spec in d["inputs"].values():
            token = spec["options"]["token"]
            tokens.update({token, token + ".earliest", token + ".latest"})
        for spec in d["visualizations"].values():
            for handler in spec.get("eventHandlers", []):
                for item in handler.get("options", {}).get("tokens", []):
                    tokens.add(item["token"])
        tokens.update((d.get("defaults", {}).get("tokens", {}).get("default") or {}).keys())
        return tokens

    def test_every_token_a_search_uses_is_set_by_something(self):
        for name, (_, d) in self.views.items():
            defined = self.defined(d)
            for ds_id, query in queries(d):
                for token in re.findall(r"\$([a-z_.]+)\$", query):
                    with self.subTest(view=name, ds=ds_id, token=token):
                        self.assertIn(token, defined)

    def test_no_view_opens_waiting_for_input(self):
        """D-J: every input has a default or picks the first result."""
        for name, (_, d) in self.views.items():
            for input_id, spec in d["inputs"].items():
                options = spec["options"]
                with self.subTest(view=name, input=input_id):
                    self.assertTrue("defaultValue" in options or options.get("selectFirstSearchResult"),
                                    "%s has no default" % input_id)

    def test_a_token_set_by_a_click_has_a_default(self):
        """Otherwise the panel that reads it waits until someone clicks."""
        for name, (_, d) in self.views.items():
            defaults = set((d.get("defaults", {}).get("tokens", {}).get("default") or {}).keys())
            defaults.update(i["options"]["token"] for i in d["inputs"].values() if "defaultValue" in i["options"])
            for spec in d["visualizations"].values():
                for handler in spec.get("eventHandlers", []):
                    for item in handler.get("options", {}).get("tokens", []):
                        with self.subTest(view=name, token=item["token"]):
                            self.assertIn(item["token"], defaults)


class AlertTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.saved = conf(os.path.join(APP, "default", "savedsearches.conf"))

    def test_the_app_ships_alerts(self):
        """D-S: the menu linked to alerts and there were none."""
        self.assertGreaterEqual(len(self.saved.sections()), 8)

    def test_every_alert_ships_disabled(self):
        for name in self.saved.sections():
            with self.subTest(alert=name):
                self.assertEqual(self.saved[name].get("disabled"), "1")

    def test_every_alert_is_scheduled_and_tracked(self):
        for name in self.saved.sections():
            section = self.saved[name]
            with self.subTest(alert=name):
                self.assertEqual(section.get("enableSched"), "1")
                self.assertTrue(section.get("cron_schedule"))
                self.assertEqual(section.get("alert.track"), "1")
                self.assertTrue(section.get("description"))

    def test_alerts_read_the_shared_thresholds(self):
        """A threshold changed in local/macros.conf must move the panel and
        the alert together."""
        for name in self.saved.sections():
            search = self.saved[name].get("search")
            with self.subTest(alert=name):
                self.assertNotRegex(search, r">=\s*\d{2}\b", "a hardcoded percentage")


class MacroTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.macros = conf(os.path.join(APP, "default", "macros.conf"))

    def test_the_health_macros_exist(self):
        for name in ("nifi_fleet", "nifi_health", "nifi_repositories", "nifi_default_interval",
                     "nifi_stale_factor", "nifi_threshold_heap", "nifi_threshold_heap_critical",
                     "nifi_threshold_repo", "nifi_threshold_repo_critical", "nifi_threshold_backpressure",
                     "nifi_threshold_bulletins", "nifi_threshold_bulletins_degraded",
                     "nifi_backpressure_horizon", "nifi_heap_sustained_samples",
                     "nifi_recent_window", "nifi_thresholds", "nifi_instance_thresholds"):
            with self.subTest(macro=name):
                self.assertIn(name, self.macros.sections())

    def test_repositories_are_read_one_per_identifier(self):
        """D-R: content and provenance are arrays."""
        definition = self.macros["nifi_repositories"]["definition"]
        for repo in ("contentRepositoryStorageUsage{}", "provenanceRepositoryStorageUsage{}"):
            with self.subTest(repo=repo):
                self.assertIn(repo + ".identifier", definition)
                self.assertIn(repo + ".usedSpaceBytes", definition)

    def test_health_names_every_state(self):
        definition = self.macros["nifi_health"]["definition"]
        for state in ("no_data", "stale", "critical", "degraded", "ok"):
            with self.subTest(state=state):
                self.assertIn('"%s"' % state, definition)


if __name__ == "__main__":
    unittest.main()


class ThresholdTest(unittest.TestCase):
    """A threshold lives in one place and can be set per instance.

    The KPIs used to colour heap at 85/95 and repositories at 80/90 written
    into the view, so changing nifi_threshold_heap moved the health and the
    alert but not the colour of the number next to them. And every instance
    shared one set of thresholds, which a fleet of very different NiFis
    cannot live with.
    """

    COLUMNS = ("heap_threshold", "heap_threshold_critical", "repo_threshold",
               "repo_threshold_critical", "backpressure_threshold", "bulletin_threshold")

    @classmethod
    def setUpClass(cls):
        cls.views = load_views()
        cls.macros = conf(os.path.join(APP, "default", "macros.conf"))
        cls.saved = conf(os.path.join(APP, "default", "savedsearches.conf"))
        cls.collections = conf(os.path.join(APP, "default", "collections.conf"))
        cls.transforms = conf(os.path.join(APP, "default", "transforms.conf"))
        with open(os.path.join(APP, "default", "props.conf"), encoding="utf-8") as handle:
            cls.props = handle.read()

    def test_no_view_colours_a_value_by_a_number_written_in_it(self):
        """Only counts (zero or more) may be coloured by a range in the view;
        a percentage threshold comes from the search, per instance."""
        for name, (_, d) in self.views.items():
            for viz_id, spec in d["visualizations"].items():
                for entry in (spec.get("context") or {}).get("majorColorEditorConfig", []):
                    with self.subTest(view=name, viz=viz_id):
                        self.assertIn(entry.get("from", 0), (0, 1))

    def test_the_inventory_declares_every_threshold_column(self):
        fields_list = self.transforms["instance"]["fields_list"]
        for column in self.COLUMNS:
            with self.subTest(column=column):
                self.assertEqual(self.collections["instance"].get("field." + column), "number")
                self.assertIn(column, fields_list)

    def test_every_column_overrides_its_macro_and_falls_back_on_garbage(self):
        """default_match fills every column of an unlisted host with
        "standalone": tonumber() is what makes that fall back to the macro."""
        definition = self.macros["nifi_thresholds"]["definition"]
        for column in self.COLUMNS:
            with self.subTest(column=column):
                self.assertIn("tonumber(%s)" % column, definition)

    def test_the_automatic_lookup_adds_only_the_cluster(self):
        """A bare OUTPUT would stamp the threshold columns -- "standalone" for
        an unlisted host -- into every event."""
        for line in self.props.splitlines():
            if line.startswith("LOOKUP-instance"):
                with self.subTest(line=line):
                    self.assertTrue(line.rstrip().endswith("OUTPUT cluster"), line)

    def test_health_uses_the_instance_thresholds(self):
        definition = self.macros["nifi_health"]["definition"]
        for name in ("heap_warn", "heap_crit", "repo_warn", "repo_crit",
                     "nifi_threshold_bulletins_degraded"):
            with self.subTest(name=name):
                self.assertIn(name, definition)
        self.assertIn("`nifi_thresholds`", self.macros["nifi_fleet"]["definition"])

    def test_no_alert_hardcodes_a_window_or_a_count(self):
        for name in self.saved.sections():
            search = self.saved[name].get("search")
            with self.subTest(alert=name):
                self.assertNotIn("3600000", search)
                self.assertNotRegex(search, r"n <= \d")
                self.assertNotIn("`nifi_threshold_heap`", search)
                self.assertNotIn("`nifi_threshold_repo`", search)
                self.assertNotIn("`nifi_threshold_backpressure`", search)
